/** Static core routes included in sitemap (not in page registry). */
export const STATIC_CORE_PATHS = [
  "/",
  "/about/",
  "/contact/",
  "/gallery/",
  "/projects/",
  "/testimonials/",
  "/faq/",
  "/pricing-guide/",
  "/materials-guide/",
  "/installation-process/",
  "/safety-guide/",
  "/privacy-policy/",
  "/terms-and-conditions/",
  "/disclaimer/",
  "/services/",
  "/locations/",
  "/solutions/",
  "/property-types/",
  "/guides/",
  "/blog/",
  "/sitemap-page/",
] as const;
