import { INTENT_KEYWORD_MENU_COLUMNS } from "@/data/intent-keyword-expansion";

export type MegaMenuColumn = {
  title: string;
  href: string;
  links: Array<{ label: string; href: string }>;
};

const S = {
  invisible: "/services/invisible-grills/",
  balconyGrill: "/services/balcony-safety-grills/",
  windowGrill: "/services/window-invisible-grills/",
  childGrill: "/services/children-safety-grills/",
  petGrill: "/services/pet-safety-grills/",
  safety: "/services/safety-nets/",
  balconyNet: "/services/balcony-safety-nets/",
  childNet: "/services/children-safety-nets/",
  kidsNet: "/services/kids-safety-nets/",
  petNet: "/services/pet-safety-nets/",
  buildingNet: "/services/building-safety-nets/",
  bird: "/services/bird-nets/",
  spikes: "/services/bird-spikes/",
  monkey: "/services/monkey-nets/",
  sports: "/services/sports-nets/",
  cloth: "/services/cloth-hangers/",
  ceilingCloth: "/services/ceiling-cloth-hangers/",
  mosquito: "/services/mosquito-nets/",
} as const;

/**
 * High-intent mega menu labels for SEO navigation.
 * Every href points to a real published page (service, property type, guide, or hub).
 * Modifier keywords map to the closest parent page — no thin doorway URLs.
 */
export const SERVICES_MEGA_MENU: MegaMenuColumn[] = [
  {
    title: "Invisible Grills",
    href: S.invisible,
    links: [
      { label: "Invisible Grills", href: S.invisible },
      { label: "Balcony Invisible Grills", href: S.balconyGrill },
      { label: "Window Invisible Grills", href: S.windowGrill },
      { label: "Stainless Steel Invisible Grills", href: S.invisible },
      { label: "SS304 Invisible Grills", href: "/materials-guide/" },
      { label: "SS316 Invisible Grills", href: "/materials-guide/" },
      { label: "Child Safety Grills", href: S.childGrill },
      { label: "Pet Safety Grills", href: S.petGrill },
      { label: "Apartment Invisible Grills", href: "/property-types/apartments/invisible-grills/" },
      { label: "Villa Invisible Grills", href: "/property-types/villas/invisible-grills/" },
      { label: "Terrace Invisible Grills", href: S.balconyGrill },
      { label: "Duplex Invisible Grills", href: "/property-types/independent-houses/invisible-grills/" },
      { label: "Invisible Grill Installation", href: "/installation-process/" },
      { label: "Invisible Grill Repair", href: "/contact/" },
      { label: "Invisible Grill Replacement", href: "/solutions/heavy-grill-replacement/" },
    ],
  },
  {
    title: "Safety Nets",
    href: S.safety,
    links: [
      { label: "Balcony Safety Nets", href: S.balconyNet },
      { label: "Children Safety Nets", href: S.childNet },
      { label: "Kids Safety Nets", href: S.kidsNet },
      { label: "Pet Safety Nets", href: S.petNet },
      { label: "Cat Safety Nets", href: S.petNet },
      { label: "Dog Safety Nets", href: S.petNet },
      { label: "Window Safety Nets", href: S.safety },
      { label: "Staircase Safety Nets", href: S.safety },
      { label: "Duct Area Safety Nets", href: S.buildingNet },
      { label: "Terrace Safety Nets", href: S.balconyNet },
      { label: "Building Safety Nets", href: S.buildingNet },
      { label: "Construction Safety Nets", href: S.buildingNet },
      { label: "Fall Protection Nets", href: S.safety },
      { label: "Industrial Safety Nets", href: S.buildingNet },
      { label: "Warehouse Safety Nets", href: S.buildingNet },
      { label: "Roof Safety Nets", href: S.buildingNet },
    ],
  },
  {
    title: "Bird & Pigeon Nets",
    href: S.bird,
    links: [
      { label: "Pigeon Safety Nets", href: S.bird },
      { label: "Balcony Pigeon Nets", href: S.bird },
      { label: "Bird Nets", href: S.bird },
      { label: "Anti Bird Nets", href: S.bird },
      { label: "Pigeon Control Nets", href: S.bird },
      { label: "Pigeon Protection Nets", href: S.bird },
      { label: "Balcony Bird Nets", href: S.bird },
      { label: "Window Bird Nets", href: S.bird },
      { label: "Duct Bird Nets", href: S.bird },
      { label: "Bird Spikes", href: S.spikes },
      { label: "Bird Control Systems", href: S.bird },
      { label: "Bird Deterrent Nets", href: S.bird },
      { label: "Solar Panel Bird Nets", href: S.bird },
      { label: "Warehouse Bird Nets", href: S.bird },
      { label: "Factory Bird Nets", href: S.bird },
    ],
  },
  {
    title: "Sports Nets",
    href: S.sports,
    links: [
      { label: "Cricket Practice Nets", href: S.sports },
      { label: "Cricket Box Nets", href: S.sports },
      { label: "Cricket Cage Nets", href: S.sports },
      { label: "Cricket Pitch Nets", href: S.sports },
      { label: "Cricket Turf Nets", href: S.sports },
      { label: "Football Nets", href: S.sports },
      { label: "Volleyball Nets", href: S.sports },
      { label: "Badminton Nets", href: S.sports },
      { label: "Tennis Nets", href: S.sports },
      { label: "Golf Nets", href: S.sports },
      { label: "Hockey Nets", href: S.sports },
      { label: "Basketball Nets", href: S.sports },
      { label: "Ball Stop Nets", href: S.sports },
      { label: "Stadium Nets", href: S.sports },
      { label: "Sports Ground Nets", href: S.sports },
      { label: "Playground Nets", href: S.sports },
    ],
  },
  {
    title: "Home Utility",
    href: S.cloth,
    links: [
      { label: "Cloth Hangers", href: S.cloth },
      { label: "Ceiling Cloth Hangers", href: S.ceilingCloth },
      { label: "Automatic Cloth Hangers", href: S.ceilingCloth },
      { label: "Motorized Cloth Hangers", href: S.ceilingCloth },
      { label: "Pulley Cloth Hangers", href: S.ceilingCloth },
      { label: "Wall Mounted Cloth Hangers", href: S.cloth },
      { label: "Balcony Drying Systems", href: "/solutions/balcony-drying-space/" },
      { label: "Laundry Drying Systems", href: S.ceilingCloth },
      { label: "Utility Area Covers", href: S.cloth },
      { label: "Balcony Covers", href: S.balconyNet },
      { label: "Polycarbonate Sheets", href: "/contact/" },
      { label: "Shade Nets", href: S.sports },
    ],
  },
  {
    title: "Mosquito & Protection",
    href: S.mosquito,
    links: [
      { label: "Mosquito Nets", href: S.mosquito },
      { label: "Window Mosquito Nets", href: S.mosquito },
      { label: "Door Mosquito Nets", href: S.mosquito },
      { label: "Pleated Mosquito Nets", href: S.mosquito },
      { label: "Sliding Mosquito Nets", href: S.mosquito },
      { label: "Magnetic Mosquito Nets", href: S.mosquito },
      { label: "Roller Mosquito Nets", href: S.mosquito },
      { label: "Insect Screens", href: S.mosquito },
      { label: "Zip Screens", href: S.mosquito },
      { label: "Motorized Zip Screens", href: S.mosquito },
      { label: "Balcony Mosquito Nets", href: S.mosquito },
      { label: "Invisible Mosquito Screens", href: S.mosquito },
    ],
  },
  {
    title: "Animal Protection",
    href: S.monkey,
    links: [
      { label: "Monkey Safety Nets", href: S.monkey },
      { label: "Cat Safety Nets", href: S.petNet },
      { label: "Dog Safety Nets", href: S.petNet },
      { label: "Pet Balcony Nets", href: S.petNet },
      { label: "Monkey Control Nets", href: S.monkey },
      { label: "Animal Protection Nets", href: S.monkey },
      { label: "Tree Protection Nets", href: S.monkey },
      { label: "Zoo Safety Nets", href: S.buildingNet },
    ],
  },
  {
    title: "Property Types",
    href: "/property-types/",
    links: [
      { label: "Apartments", href: "/property-types/apartments/invisible-grills/" },
      { label: "Villas", href: "/property-types/villas/invisible-grills/" },
      { label: "Independent Houses", href: "/property-types/independent-houses/invisible-grills/" },
      { label: "Duplex Houses", href: "/property-types/independent-houses/invisible-grills/" },
      { label: "Gated Communities", href: "/property-types/apartments/invisible-grills/" },
      { label: "High Rise Apartments", href: "/property-types/high-rise-apartments/invisible-grills/" },
      { label: "Residential Buildings", href: "/property-types/apartments/safety-nets/" },
      { label: "Commercial Buildings", href: "/property-types/" },
      { label: "Office Buildings", href: "/property-types/" },
      { label: "Schools", href: "/property-types/" },
      { label: "Colleges", href: "/property-types/" },
      { label: "Hospitals", href: "/property-types/" },
      { label: "Hotels", href: "/property-types/" },
      { label: "Restaurants", href: "/property-types/" },
      { label: "Shopping Malls", href: "/property-types/" },
      { label: "Warehouses", href: "/property-types/" },
      { label: "Factories", href: "/property-types/" },
      { label: "Industrial Buildings", href: "/property-types/high-rise-apartments/building-safety-nets/" },
    ],
  },
  {
    title: "Solutions Hub",
    href: "/solutions/",
    links: [
      { label: "Safety Net Price", href: "/pricing-guide/" },
      { label: "Invisible Grill Price", href: "/pricing-guide/" },
      { label: "Bird Net Price", href: "/pricing-guide/" },
      { label: "Cloth Hanger Price", href: "/pricing-guide/" },
      { label: "Installation Guide", href: "/installation-process/" },
      { label: "Buying Guide", href: "/guides/invisible-grill-pricing-factors/" },
      { label: "Maintenance Guide", href: "/guides/invisible-grill-material-guide/" },
      { label: "Repair Services", href: "/contact/" },
      { label: "Comparison Guide", href: "/guides/invisible-grills-vs-safety-nets/" },
      { label: "FAQs", href: "/faq/" },
      { label: "Blog", href: "/blog/" },
      { label: "Case Studies", href: "/projects/" },
      { label: "Customer Reviews", href: "/testimonials/" },
      { label: "Gallery", href: "/gallery/" },
      { label: "Warranty", href: "/faq/" },
      { label: "Service Areas", href: "/locations/" },
    ],
  },
  {
    title: "High-Intent Searches",
    href: "/services/",
    links: [
      { label: "Invisible Grills Near Me", href: "/invisible-grills-in-chennai/" },
      { label: "Safety Nets Near Me", href: "/safety-nets-in-chennai/" },
      { label: "Pigeon Nets Near Me", href: "/bird-nets-in-chennai/" },
      { label: "Balcony Pigeon Nets", href: S.bird },
      { label: "Balcony Bird Nets", href: S.bird },
      { label: "Bird Net Installation", href: S.bird },
      { label: "Pigeon Net Installation", href: S.bird },
      { label: "Child Balcony Safety Nets", href: S.childNet },
      { label: "Apartment Balcony Safety Nets", href: "/property-types/apartments/balcony-safety-nets/" },
      { label: "Balcony Safety Mesh", href: S.balconyNet },
      { label: "Balcony Protection Nets", href: S.balconyNet },
      { label: "Anti Pigeon Nets", href: S.bird },
      { label: "Bird Proof Balcony", href: "/solutions/pigeon-balcony-control/" },
      { label: "Cat Balcony Nets", href: S.petNet },
      { label: "Dog Balcony Nets", href: S.petNet },
      { label: "Monkey Proof Nets", href: S.monkey },
      { label: "Invisible Balcony Protection", href: S.balconyGrill },
      { label: "Balcony Grill Safety", href: S.balconyGrill },
      { label: "Stainless Steel Balcony Grills", href: S.balconyGrill },
      { label: "Home Safety Solutions", href: "/solutions/" },
      { label: "Balcony Fall Protection", href: "/solutions/child-balcony-safety/" },
      { label: "High Rise Safety Nets", href: "/property-types/high-rise-apartments/safety-nets/" },
      { label: "Terrace Bird Nets", href: S.bird },
      { label: "Window Bird Nets", href: S.bird },
      { label: "Duct Area Bird Nets", href: S.bird },
      { label: "Construction Debris Nets", href: S.buildingNet },
      { label: "Building Protection Nets", href: S.buildingNet },
      { label: "Sports Ground Nets", href: S.sports },
      { label: "Turf Cricket Nets", href: S.sports },
      { label: "Swimming Pool Safety Nets", href: S.safety },
      { label: "Shade Net Installation", href: S.sports },
      { label: "Drying Cloth Hanger Systems", href: S.ceilingCloth },
      { label: "Motorized Drying Systems", href: S.ceilingCloth },
      { label: "Cricket Practice Nets", href: S.sports },
      { label: "Cricket Box Nets", href: S.sports },
      { label: "Cricket Cage Nets", href: S.sports },
      { label: "Bird Mesh Installation", href: S.bird },
    ],
  },
  ...INTENT_KEYWORD_MENU_COLUMNS,
];

export const AREAS_MEGA_MENU: MegaMenuColumn[] = [
  {
    title: "Coimbatore",
    href: "/locations/coimbatore/",
    links: [
      { label: "Coimbatore", href: "/locations/coimbatore/" },
      { label: "RS Puram", href: "/locations/coimbatore/rs-puram/" },
      { label: "Saibaba Colony", href: "/locations/coimbatore/saibaba-colony/" },
      { label: "Race Course", href: "/locations/coimbatore/race-course/" },
      { label: "Gandhipuram", href: "/locations/coimbatore/gandhipuram/" },
      { label: "Peelamedu", href: "/locations/coimbatore/peelamedu/" },
      { label: "Saravanampatti", href: "/locations/coimbatore/saravanampatti/" },
      { label: "Singanallur", href: "/locations/coimbatore/singanallur/" },
      { label: "Vadavalli", href: "/locations/coimbatore/vadavalli/" },
      { label: "Ganapathy", href: "/locations/coimbatore/ganapathy/" },
      { label: "Avinashi Road", href: "/locations/coimbatore/avinashi-road/" },
      { label: "Trichy Road", href: "/locations/coimbatore/trichy-road/" },
      { label: "Thudiyalur", href: "/locations/coimbatore/thudiyalur/" },
      { label: "Kalapatti", href: "/locations/coimbatore/kalapatti/" },
      { label: "Sulur", href: "/locations/coimbatore/sulur/" },
      { label: "Pollachi", href: "/locations/pollachi/" },
      { label: "Mettupalayam", href: "/locations/mettupalayam/" },
    ],
  },
  {
    title: "Chennai",
    href: "/locations/chennai/",
    links: [
      { label: "Chennai", href: "/locations/chennai/" },
      { label: "Adyar", href: "/locations/chennai/adyar/" },
      { label: "Velachery", href: "/locations/chennai/velachery/" },
      { label: "Anna Nagar", href: "/locations/chennai/anna-nagar/" },
      { label: "T Nagar", href: "/locations/chennai/t-nagar/" },
      { label: "Thiruvanmiyur", href: "/locations/chennai/thiruvanmiyur/" },
      { label: "Sholinganallur", href: "/locations/chennai/sholinganallur/" },
      { label: "Tambaram", href: "/locations/chennai/tambaram/" },
      { label: "Porur", href: "/locations/chennai/porur/" },
      { label: "OMR", href: "/locations/chennai/sholinganallur/" },
    ],
  },
  {
    title: "All Tamil Nadu",
    href: "/locations/",
    links: [
      { label: "Madurai", href: "/locations/madurai/" },
      { label: "Tiruchirappalli", href: "/locations/tiruchirappalli/" },
      { label: "Salem", href: "/locations/salem/" },
      { label: "Tiruppur", href: "/locations/tiruppur/" },
      { label: "Erode", href: "/locations/erode/" },
      { label: "Hosur", href: "/locations/hosur/" },
      { label: "Vellore", href: "/locations/vellore/" },
      { label: "Tirunelveli", href: "/locations/tirunelveli/" },
      { label: "Nagercoil", href: "/locations/nagercoil/" },
      { label: "Thanjavur", href: "/locations/thanjavur/" },
      { label: "Karur", href: "/locations/karur/" },
      { label: "Dindigul", href: "/locations/dindigul/" },
      { label: "Ooty", href: "/locations/ooty/" },
      { label: "All locations", href: "/locations/" },
    ],
  },
];
